In [1]:
### import package

import numpy as np


### Numpy array

In [5]:
distance = [55, 60, 45]
speed = [6, 7, 10]
dist = np.array(distance)
print(dist)
spd = np.array(speed)
print(spd)

time = dist/spd
print(time)

[55 60 45]
[ 6  7 10]
[9.16666667 8.57142857 4.5       ]


### Numpy array atributes

In [8]:
## kieu du  lieu cua array
print("data of type array: ", time.dtype)

## chieu cua array
print('no. of dimensions: ', time.ndim)

## kich co cua tung chieu trong array
print('size of dimension: ', time.shape)

## 
print("total size of array: ", time.size)

data of type array:  float64
no. of dimensions:  1
size of dimension:  (3,)
total size of array:  3


### Creating numpy array

In [15]:

### khoi tao bo sinh so ngau nhien
np.random.seed(15)

x1 = np.random.randint(10, size=6) # mang 1 chieu
x2 = np.random.randint(10, size=(3, 4)) # mang 2 chieu
x3 = np.random.randint(10, size=(4, 5, 6)) #mang 3 chieu


print("x1 dim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)
print("\n")
print("x2 dim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)
print("\n")
print("x3 dim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x1 dim:  1
x1 shape:  (6,)
x1 size:  6


x2 dim:  2
x2 shape:  (3, 4)
x2 size:  12


x3 dim:  3
x3 shape:  (4, 5, 6)
x3 size:  120


In [17]:
## np.arrange : sinh chuoi 
f = np.arange(10, 20, 2)

print(f)

[10 12 14 16 18]


### Accessing an element of a NumPy array
truy cap vao cac phan tu trong array

In [22]:
print("1-d array", x1)

print(f"phan tu thu 3: {x1[2]}")
print(f"phan tu cuoi: {x1[-1]}")
print(f"phan tu thu dua tien: {x1[0]}")

1-d array [8 5 5 7 0 7]
phan tu thu 3: 5
phan tu cuoi: 7
phan tu thu dua tien: 8


In [31]:
print("2D array: \n", x2)
print(f"X2[0][0] = {x2[0, 0]}")
print(f"X2[2][1] = {x2[2, 1]}")

print("\n3D array: \n", x3)
print(f"x3[2][[2][1]] = {x3[2, 2, 1]}")
print(f"x3[0][[4][2]] = {x3[0, 4, 2]}")

2D array: 
 [[5 6 1 7]
 [0 4 9 7]
 [5 3 6 8]]
X2[0][0] = 5
X2[2][1] = 3

3D array: 
 [[[2 1 1 0 5 2]
  [2 1 8 5 6 9]
  [2 8 6 8 8 3]
  [4 7 2 0 5 7]
  [3 8 5 3 1 0]]

 [[8 7 5 8 1 2]
  [8 3 1 3 7 2]
  [7 2 0 0 7 6]
  [4 4 3 7 5 6]
  [0 9 0 4 8 6]]

 [[3 2 7 4 2 2]
  [9 3 3 4 3 5]
  [3 0 0 6 1 2]
  [2 1 4 7 8 7]
  [2 5 3 8 9 4]]

 [[9 4 4 1 0 4]
  [7 8 5 9 3 0]
  [4 0 1 9 4 5]
  [4 8 3 9 1 3]
  [5 1 6 7 0 9]]]
x3[2][[2][1]] = 0
x3[0][[4][2]] = 5


### Slicing in NumPy array

In [39]:
### 1D array

x = np.arange(10)
print(x)

print("first five element: ", x[:5])
print("element after index 5: ", x[5:])
print("middle sub-array: ", x[4:7])
print("every other element: ", x[::2])
print("every other element, starting index 1: ", x[1::2])
print("element reversed: ", x[::-1])

[0 1 2 3 4 5 6 7 8 9]
first five element:  [0 1 2 3 4]
element after index 5:  [5 6 7 8 9]
middle sub-array:  [4 5 6]
every other element:  [0 2 4 6 8]
every other element, starting index 1:  [1 3 5 7 9]
element reversed:  [9 8 7 6 5 4 3 2 1 0]


In [42]:
## 2D array

print(x2)
print("two rows, three columns: \n", x2[:2, :3])

[[5 6 1 7]
 [0 4 9 7]
 [5 3 6 8]]
two rows, three columns: 
 [[5 6 1]
 [0 4 9]]


In [56]:
## copy fuction

### original array
print("original 2D array: \n", x2)

### copy mang 2x2 tu x2
x2_sub = x2[:2, :2]
print("sub-array: \n", x2_sub)

## thay doi gia tri
x2_sub[0, 0] = 15
print("modified array: \n", x2_sub)

### original array after sub-array changes
print("\noriginal array after sub-array changes:\n", x2)
print("\nmaking coy of the original array: \n")
x2_sub_cp = x2[:2, :2].copy()
print(x2_sub_cp)


## thay doi gia tri

x2_sub_cp[0, 0] = 22
print("modyfying x2:\n", x2)

original 2D array: 
 [[15  6  1  7]
 [ 0  4  9  7]
 [ 5  3  6  8]]
sub-array: 
 [[15  6]
 [ 0  4]]
modified array: 
 [[15  6]
 [ 0  4]]

original array after sub-array changes:
 [[15  6  1  7]
 [ 0  4  9  7]
 [ 5  3  6  8]]

making coy of the original array: 

[[15  6]
 [ 0  4]]
modyfying x2:
 [[15  6  1  7]
 [ 0  4  9  7]
 [ 5  3  6  8]]


### Array concatenation

In [57]:
## creating two sample array
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [58]:
## create a sample array
x = np.array([1, 2, 3])
grid = np.array([[3, 4, 5],
                [7, 8, 9]])
np.vstack([x, grid])

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [59]:
### horizontally stack the arrays

y = np.array([[99],
             [99]])

np.hstack([grid, y])

array([[ 3,  4,  5, 99],
       [ 7,  8,  9, 99]])